### ISSUE TITLE
plumble crashes

### ISSUE THREAD

**Issue by porjo** [mumble-voip/grumble#30]
Plumble (the Android client) crashes when attempting to connect to Grumble.

I'm running Grumble on my laptop, and connecting from my Android phone over wifi. It consistently crashes when I attempt to connect to the server.  The Grumble log just shows this:

```
[1] 2018/08/28 15:01:37.390964 <2:(-1)> New connection: 10.0.0.121:45837 (2)
[1] 2018/08/28 15:01:44.005798 <2:phone(-1)> Disconnected
```

No crash Plumble to Murmur (also running on my laptop)
No crash Qt Client to Grumble

(Using Plumble 3.3.0-rc1 on Android 8.1.0)

**Comment by bontibon** [comment]
Since Plumble is crashing and not Grumble, I would submit the issue to the Plumble project. A new issue can be opened here If there a specific defect in Grumble.
