### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by rafaelbonifaz** [mumble-voip/grumble#41]
Hi,
I tried to install running `go get mumble.info/grumble/cmd/grumble` as explained in the [README](https://github.com/mumble-voip/grumble/blob/master/README.md), but it does not work. I get the following error:

```
$ go get mumble.info/grumble/cmd/grumble
package mumble.info/grumble/cmd/grumble: unrecognized import path "mumble.info/grumble/cmd/grumble" (parse https://mumble.info/grumble/cmd/grumble?go-get=1: no go-import meta tags ())
```
Using the Docker instructions works fine. 

I think documentation should be updated.

Thanks a lot for this nice project!

**Comment by olabiniV2** [comment]
@davidebeatrici - any ideas on whether it would be possible to put back the right behavior on mumble.info? I assume it used to work.

The basic idea is that `https://mumble.info/grumble/cmd/grumble?go-get=1` needs to return HTML that contains something like this:
`<meta name="go-import" content="mumble.info git https://github.com/mumble-voip/grumble">`

**Comment by davidebeatrici** [comment]
Fixed, the issue was `AH00687`.

Apache was not finding the script when rewriting the URL because its extension was not handled.

**Comment by olabiniV2** [comment]
Very nice, @davidebeatrici - it works great now. Thanks!

**Comment by rafaelbonifaz** [comment]
Thank you very much, it works now!
