### ISSUE TITLE
Server password configuration

### ISSUE THREAD

**Issue by peterpalau** [mumble-voip/grumble#49]
Is there any way to set a password for the server?

**Comment by olabiniV2** [comment]
We implemented support for Server passwords and also user authentication like this, for now:
https://github.com/digitalautonomy/grumble/commit/d24046b1b77ac2b885db0874df43d6f13be66791

If it's interesting, I can easily adapt it and create a PR for mainline Grumble.

**Comment by actown** [comment]
Merged with #55
