### ISSUE TITLE
I want to give grumble (and therefore mumble) the 2016 treatment

### ISSUE THREAD

**Issue by faddat** [mumble-voip/grumble#8]
With Mumble you've got to use ice + front end to get access to it.  But, many mumble chats are connected to a web community in some way, shape or form, and form should follow function.  So, here's what I'm thinking and greatly appreciate thoughts and criticism on:
- Add the api
- Add a (since it's 2016) react.js front end
- Add a CLI UI based on Cobra
- Add a viper-based configuration system
- Ensure that grumble is capable of steaming audio to a web page in an open format that works with all evergreen browsers
- Ensure that users can easily join that streaming audio conversation using an evergreen browser

Overall goal:  Serve all of this from a single distributed binary (the static files can be compressed into the executable using one of a number of various go packages/libraries) and then let it fly.  I'm writing to  get next-steps on this and get a feel for other users needs.  

Thanks!

**Comment by mkrautz** [comment]
Hi Jacob.

This is great. The general goals: API, Web UI, CLI UI, and an improved configuration system, and bridging Mumble to the web are all features we need.

Of the above, the ones *I* am interested in working on are getting the protocol bridged to the web. The first step would be to expose the Mumble protocol via websockets. See https://github.com/mumble-voip/mumble/issues/2131.

I am not going to have much time to look at any of the other stuff, so if you're interested in hacking on it, please go ahead. I am happy to review any changes -- or, if you wish, I can make you the grumble maintainer and give you commit access. I don't know if you have the time to commit to it -- but if we could kickstart the development, it would be awesome.

It would be wonderful if we could ship everything from your list above in a single static binary, and easily build that static binary as well. Most of my time these days are spent on maintaining our build environments for

**Comment by faddat** [comment]
So, I'm going to have time in a couple of weeks.  I'm doing dev work for two mumble users at the moment, and they want their pages to be more interactive in terms of the experience with their raido shows.  

I should say-- I'm not all that familiar with the mumble-using gaming community, both of my clients run crypto/fintech related interactive radio programs.  So, once I am done getting a couple of databases to eat a blockchain's blocks, I'll be able to dedicate some real time to improving grumble :).  I'm curious:  Any idea how to go about surveying users of grumble/mumble?  I figure that getting user stories in place now can only help guide the dev process once I get rolling....

**Comment by mkrautz** [comment]
If there is still interest, please ping this thread or me. For now, I'll close it. :-)
